# Generated by Django 4.2.16 on 2024-11-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                ("course_id", models.IntegerField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=100)),
                ("course_teacher", models.CharField(max_length=100)),
            ],
        ),
    ]
